export const
	BREAD_BOTTOM = "BREAD_BOTTOM",
	BREAD_TOP = "BREAD_TOP",
	MEAT = "MEAT",
	CHEESE = "CHEESE",
	SALAD = "SALAD",
	BACON = "BACON",
	
	INGREDIENT_PRICE = {
		SALAD: 0.4,
		CHEESE: 0.5,
		MEAT: 1.3,
		BACON: 0.7
	}